sudo: required
dist: trusty
language: csharp
services:
  - docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - ARTIFACTS_PATHS=./artifacts
  - AWS_ACCESS_KEY_ID=MOCK_ID
  - AWS_SECRET_ACCESS_KEY=MOCK_SECRET_KEY
  - AWS_SESSION_TOKEN=MOCK_SESSION_TOKEN
  - secure: "H5wkF2579efgwqXuduwoxyEVQP+GzKtTGA7sjgMkhkHdpKjnjB0g4MKjVjAaMuG1l4GOwqdVztv6U17yE49oWlO2MkAFe3ElMZsTt1DRb0djx5NEqmtyHFxiBCZ2aKD0Hl5jnQubqgknKS5sOwOQtktT5amIl6+LdgXWEfDXEJ0RdSOr3/DzaXbn/cMsZa9IVZFa0lSU+GMmC4Y7RmjGDlj/0i3GdrKJ6poOXX5H37x0isfTndCmzX7guKdFpZCK4aMrc99XoSxqLPrGMumpjm1lP1N79F8N4h3iYjEa/GAPTIqVcJOv5uRmAcmLrjm1Jb2QrrpUh7sUWovgMJ0il/LVMWu+5rvy4QZ+GMSSkOWBNue0JoCNTUUauXoS5YWUAU9pWnZJOp6n2p53o6rb0j530HhBmQdGIE7rWVwO23tajbNiPNEiFEe6M9ZQ5hhWxE8pCqSzcS8x7uWxAp6Q42JwO2tYi9GYpVr+G8rKYyoyBpqlDql7EdAqetz/X4Y1jHW4ATIpZE9ldFHzEwt29aAeXB91yA8dIoPdfGr8idzQn5i/9XQ9esKM9siTQtdqP23RYo2uA3CFmOEyJc32kEsgg+dtJ2SITiU6z1W+kZoQ5M+HE5ialtP0wp1ooSlZPV3iv1zXaiGclpwAdXUXo8uHNOz4oJvPth/Y6z0RJCM="
install:
- sudo apt-get install -y jq
- sudo touch /etc/apt/sources.list.d/dotnetdev.list
- echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" | sudo tee -a /etc/apt/sources.list.d/dotnetdev.list
- sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 && sudo apt-get update
- sudo apt-get install -y --no-install-recommends dotnet-dev-1.0.0-preview2.1-003177
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install semver -g
- docker pull dwmkerr/dynamodb
before_script:
- chmod u+x build.sh
- chmod u+x ./scripts/set-build-version.sh
- chmod u+x ./scripts/patch-version.sh
- chmod u+x ./scripts/push-to-nuget.sh
- eval $(./scripts/set-build-version.sh)
- ./scripts/patch-version.sh --version=$PROJECT_BUILD_VERSION
- export PATH=$PATH:$HOME/.local/bin
- mono --version
- dotnet --info
- docker run -d -p 8000:8000 dwmkerr/dynamodb -inMemory
- docker ps -a
script:
- ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=RELEASE --outputFolder=./artifacts --pack
after_success:
- if [ ! -z "$TRAVIS_TAG" ] && semver $TRAVIS_TAG &>/dev/null; then ./scripts/push-to-nuget.sh --apikey=$NUGET_API_KEY --version=$PROJECT_BUILD_VERSION; fi