environment:
  AWS_ACCESS_KEY_ID: MOCK_ID
  AWS_SECRET_ACCESS_KEY: MOCK_SECRET_KEY
  AWS_SESSION_TOKEN: MOCK_SESSION_TOKEN
  CLI_VERSION: latest

install:
  - cinst 7zip

build_script:
  # Download and install .NET Core SDK
  - ps: Invoke-Expression "powershell 'iwr https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1 -UseBasicParsing | iex'"
  - ps: $env:PATH = "C:\Users\appveyor\AppData\Local\Microsoft\dotnet\;" + $env:PATH
  # Download and run local DynamoDB
  - ps: Start-Process -NoNewWindow powershell .\scripts\local_db.ps1
  # Restore, build, test
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build .\src\AspNetCore.Identity.DynamoDB -c Release
  - ps: dotnet build .\samples\IdentitySample.Mvc -c Release
  - ps: dotnet build .\tests\AspNetCore.Identity.DynamoDB.Tests -c Release
  - ps: dotnet test .\tests\AspNetCore.Identity.DynamoDB.Tests\AspNetCore.Identity.DynamoDB.Tests.csproj -c Release --no-build

test: off
version: '0.0.0.{build}'